version: "3.10"

services:
  backend:
    build:
      context: ./daar_backend
      dockerfile: Dockerfile
    container_name: django-backend
    ports:
      - "8000:8000"
    volumes:
      - ./daar_backend:/app
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=library_db
      - DB_USER=postgres
      - DB_PASSWORD=daar2025

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: library_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: