version: "3.10"

networks:
  app-network:
    driver: bridge
    
services:
  backend:
    image: luantoine/daar_backend:latest
    build:
      context: ./daar_backend
    container_name: django-backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./daar_backend:/app
    environment:
      - DEBUG=True
      - DB_HOST=daar2025-luluantoinex-745c.b.aivencloud.com
      - DB_PORT=25492
      - DB_NAME=defaultdb
      - DB_USER=avnadmin
      - DB_PASSWORD=AVNS_swNH8lITHgvFjg-tf5M

  frontend:
    image: luantoine/daar_frontend:latest
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app


volumes:
  postgres_data: