version: "3.10"

networks:
  app-network:
    driver: bridge
    
services:
  backend:
    image: luantoine/daar_backend:latest
    build:
      context: ./daar_backend
      dockerfile: Dockerfile
    container_name: django-backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./daar_backend:/app
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=library_db
      - DB_USER=postgres
      - DB_PASSWORD=daar2025

  frontend:
    image: luantoine/daar_frontend:latest
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  db:
    image: postgres:14
    container_name: postgres-db
    ports:
      - "5432:5432"
    networks:
      - app-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: daar2025
      POSTGRES_DB: library_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "lesA@daar.com"
      PGADMIN_DEFAULT_PASSWORD: "adminpassword"
    ports:
      - "5050:80"
    networks:
      - app-network
    depends_on:
      - db

volumes:
  postgres_data: