# Generated by Django 5.1.4 on 2025-01-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('authors', models.JSONField()),
                ('subjects', models.JSONField()),
                ('bookshelves', models.JSONField()),
                ('languages', models.JSONField()),
                ('copyright', models.BooleanField(default=False)),
                ('media_type', models.CharField(max_length=50)),
                ('download_count', models.IntegerField(default=0)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('cover_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
