# Generated by Django 5.1.4 on 2025-01-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_book_id_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='centrality',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='neighbors',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
